### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/vertical-hotel#21]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] board_frontdesk
- [x] hotel - By @darshan-serpent - #33
- [x] hotel_housekeeping - ~~By @KrishnaPrajapati-SerpentCS - #36~~ By @darshan-serpent - #41 
- [x] hotel_reservation - ~~By @KrishnaPrajapati-SerpentCS - #34>~~ By @darshan-serpent - #42 
- [x] hotel_restaurant - ~~@KrishnaPrajapati-SerpentCS - #35~~ By @darshan-serpent - #40  
- [x] report_hotel_reservation - By @KrishnaPrajapati-SerpentCS - #37 
- [x] report_hotel_restaurant - By @KrishnaPrajapati-SerpentCS - #38

**Comment by omarouhari** [comment]
is there some one to validate this migration !!

**Comment by pedrobaeza** [comment]
@omarouhari You can do it checking the PRs: https://odoo-community.org/page/review

**Comment by omarouhari** [comment]
@pedrobaeza how can I get the source code of migrated version ?

**Comment by pedrobaeza** [comment]
You have to know Git for cloning the branch or use GitHub for downloading a ZIP file, but you can try on our runbot infrastructure.

**Comment by omarouhari** [comment]
@pedrobaeza I know Git very well but there is no source code in branch 11 except readme file !!
Maybe I have to use travis !!
Thanks showing me how to use it.

**Comment by pedrobaeza** [comment]
The source is in the PRs (pull requests)

**Comment by omarouhari** [comment]
@pedrobaeza I couldn't download the source code. Can you show me how achieve this please !!

**Comment by pedrobaeza** [comment]
@omarouhari Everything is open, so what you only need to do is to know how to do it. Using GIT and cloning branches from PRs or downloading directly via tools that GitHub offers, you will get the code, but this is out of my scope as community manager for teaching you on how to do it.

I hope you understand.

**Comment by ericdai** [comment]
how to install it under odoo11？

**Comment by JayVora-SerpentCS** [comment]
@ericdai This is a work in progress. You may see the PRs and it may help you setup v11, but nt reviewed yet.

**Comment by ericdai** [comment]
when will the v11 be ready?

**Comment by vbezl** [comment]
RoomSummary widget in /hotel_reservation/static/src/js/hotel_room_summary.js - doesn't work - it doesn't catch events - this.on("_onFieldChanged:date_from", this, function() {...} doesn't catch it. I cann't figure out why...

**Comment by vijoin** [comment]
Hi.

With all respect,
Odoo 12 is about to be released and this module has not been ported to v11 yet.. I've seen several PRs and reviews but  they have not been aproved either.

Is there something I can do to get this job done quicker?

Would it make any difference to add a new review or is it something about a high ranked developer to give the "+1" ?

**Comment by pedrobaeza** [comment]
See OCA contribution guidelines for knowing the reviewing rules: https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md

**Comment by EBII** [comment]
many module migration in this issue are merged.. 
Need to migrate board_frontdesk ?
