### ISSUE TITLE
Migration to version 8

### ISSUE THREAD

**Issue by max3903** [OCA/vertical-hotel#3]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-8
# Modules to migrate
- [x] board_frontdesk
- [ ] hotel by @amoya-dx in https://github.com/Domatix/vertical-hotel/tree/mig_8.0_hotel
- [ ] hotel_housekeeping
- [ ] hotel_reservation
- [ ] hotel_restaurant
- [ ] report_hotel_reservation
- [ ] report_hotel_restaurant

**Comment by amoya-dx** [comment]
Hi, in Domatix we are working on hotel module in this branch

https://github.com/Domatix/vertical-hotel/tree/mig_8.0_hotel

**Comment by rafaelbn** [comment]
Hi @max3903 ,

Is this https://github.com/OCA/vertical-hotel dead inside OCA?

I see outside OCA there are some project but no body is working in OCA. Do you know wich is the more "oficial" project about this vertical?

Thanks
Regards

**Comment by JayVora-SerpentCS** [comment]
You are right, I was supposed to work on it, but haven't been able to port as the base version is very different than mine. If I get more reviewers added up, it will help.
Ours is https://github.com/JayVora-SerpentCS/OdooHotelManagementSystem/ fully ready to be ported.
Someone just needs to add up.

**Comment by rafaelbn** [comment]
Hi @max3903 @JayVora-SerpentCS 

I think we can close this issue. It's migrated to v10 and nobody is going to migrate to v8 IMO

**Comment by max3903** [comment]
:+1:

**Comment by elicoidal** [comment]
> Ours is https://github.com/JayVora-SerpentCS/OdooHotelManagementSystem/ fully ready to be ported.
Someone just needs to add up.

@JayVora-SerpentCS do you think you could start the port to v10?
Having a great vertical-hotel would be awesome for the OCA

**Comment by pedrobaeza** [comment]
@elicoidal, it was already moved to OCA during LLN code sprint.

**Comment by elicoidal** [comment]
Fantastic!
